# Generated by Django 5.2.1 on 2025-05-22 15:16

import pescasa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pescasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pescasa.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
