# Generated by Django 5.2.1 on 2025-05-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pescasa', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='research_areas',
        ),
        migrations.AddField(
            model_name='user',
            name='research_areas',
            field=models.ManyToManyField(blank=True, to='pescasa.researcharea'),
        ),
    ]
