[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate --settings=setup.settings_railway && python manage.py collectstatic --noinput --settings=setup.settings_railway && gunicorn setup.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[env]
DJANGO_SETTINGS_MODULE = "setup.settings_railway"
SECRET_KEY = "railway-production-key-change-in-dashboard"

# Railway-specific optimizations
[nixpacks.config]
pythonVersion = "3.11"
