# Generated by Django 5.2 on 2025-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="assets/img/no_pic.jpg",
                null=True,
                upload_to="community_pics/",
            ),
        ),
    ]
