# Generated by Django 5.2 on 2025-09-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_community_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="community",
            name="community_pic",
            field=models.ImageField(blank=True, null=True, upload_to="community_pics/"),
        ),
    ]
