# Generated by Django 5.2 on 2025-09-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_communitymessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitymessage",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="community_messages/pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="communitymessage",
            name="body",
            field=models.TextField(blank=True, help_text="Texto da mensagem."),
        ),
    ]
