# Generated by Django 5.2 on 2025-09-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0006_communitymessage_pdf_alter_communitymessage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="access_type",
            field=models.CharField(
                choices=[("free", "Gratuito"), ("paid", "Pago")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
