# Generated by Django 5.2 on 2025-09-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0009_articleaccessrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleaccessrequest",
            name="reviewed",
        ),
    ]
