# Generated by Django 5.2 on 2025-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0010_remove_articleaccessrequest_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
