# Generated by Django 5.2 on 2025-10-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
