# Generated by Django 5.2 on 2025-10-11 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_remove_post_likes_remove_post_user_delete_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('media_file', models.FileField(upload_to='media_posts/', verbose_name='Arquivo de Mídia')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], max_length=10, verbose_name='Tipo de Mídia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post de Mídia',
                'verbose_name_plural': 'Posts de Mídia',
                'ordering': ['-created_at'],
            },
        ),
    ]
