# Generated by Django 5.2 on 2025-10-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_mediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Grátis'), ('paid', 'Pago')], default='free', max_length=10, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=10, verbose_name='Tipo de Mídia'),
        ),
    ]
