# Generated by Django 5.2 on 2025-10-11 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_mediapost_payment_type_alter_mediapost_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10, verbose_name='Status')),
                ('access_granted', models.BooleanField(default=False, verbose_name='Acesso Concedido')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='feed.mediapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso à Mídia',
                'verbose_name_plural': 'Acessos à Mídia',
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'media_post')},
            },
        ),
    ]
