# Generated by Django 5.2 on 2025-10-11 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_mediaaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.mediapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário de Mídia',
                'verbose_name_plural': 'Comentários de Mídia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feed.mediapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curtida de Mídia',
                'verbose_name_plural': 'Curtidas de Mídia',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'media_post')},
            },
        ),
    ]
