# Generated by Django 5.2 on 2025-10-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_mediacomment_medialike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='mediapost',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_post', to='feed.article'),
        ),
        migrations.DeleteModel(
            name='MediaAccess',
        ),
    ]
