# Generated by Django 5.2 on 2025-10-11 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_integrate_with_article_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='article',
            field=models.OneToOneField(blank=True, help_text='Artigo para controle de acesso pago', null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.article', verbose_name='Artigo Associado'),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media_posts/', verbose_name='Arquivo de Mídia (temp)'),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='media_posts/', verbose_name='Arquivo de Mídia')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('document', 'Documento')], max_length=10, verbose_name='Tipo de Mídia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='feed.mediapost')),
            ],
            options={
                'verbose_name': 'Arquivo de Mídia',
                'verbose_name_plural': 'Arquivos de Mídia',
                'ordering': ['created_at'],
            },
        ),
    ]
