# Generated by Django 5.2 on 2025-10-11 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_remove_mediapost_media_type_alter_mediapost_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='payment_type',
            field=models.CharField(choices=[('free', 'Grátis'), ('paid', 'Pago')], default='free', max_length=10, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AddField(
            model_name='mediapost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço para conteúdo pago', max_digits=8, null=True, verbose_name='Preço (R$)'),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='article',
            field=models.OneToOneField(blank=True, help_text='Artigo para controle de acesso pago - será removido', null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.article', verbose_name='Artigo Associado (Deprecated)'),
        ),
        migrations.CreateModel(
            name='MediaAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.mediapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso a Mídia Paga',
                'verbose_name_plural': 'Acessos a Mídias Pagas',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'media_post')},
            },
        ),
        migrations.CreateModel(
            name='MediaAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_slip', models.FileField(upload_to='media_access_slips/', verbose_name='Comprovante de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('media_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.mediapost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Acesso a Mídia',
                'verbose_name_plural': 'Pedidos de Acesso a Mídias',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'media_post')},
            },
        ),
    ]
