# Generated by Django 5.2 on 2025-10-11 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_mediapost_payment_type_mediapost_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('area_pesquisa', models.CharField(choices=[('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('endocrinologia', 'Endocrinologia'), ('gastroenterologia', 'Gastroenterologia'), ('ginecologia', 'Ginecologia e Obstetrícia'), ('neurologia', 'Neurologia'), ('oftalmologia', 'Oftalmologia'), ('oncologia', 'Oncologia'), ('ortopedia', 'Ortopedia'), ('pediatria', 'Pediatria'), ('pneumologia', 'Pneumologia'), ('psiquiatria', 'Psiquiatria'), ('urologia', 'Urologia'), ('anestesiologia', 'Anestesiologia'), ('radiologia', 'Radiologia'), ('patologia', 'Patologia'), ('medicina_geral', 'Medicina Geral'), ('saude_publica', 'Saúde Pública'), ('enfermagem', 'Enfermagem'), ('fisioterapia', 'Fisioterapia'), ('farmacia', 'Farmácia'), ('nutricao', 'Nutrição'), ('odontologia', 'Odontologia'), ('medicina_veterinaria', 'Medicina Veterinária'), ('tecnologia_saude', 'Tecnologia em Saúde'), ('outros', 'Outros')], max_length=50, verbose_name='Área de Pesquisa')),
                ('link', models.URLField(verbose_name='Link do Produto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
