# Generated by Django 5.2 on 2025-10-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='research_area',
            field=models.CharField(choices=[('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('endocrinologia', 'Endocrinologia'), ('gastroenterologia', 'Gastroenterologia'), ('ginecologia', 'Ginecologia e Obstetrícia'), ('neurologia', 'Neurologia'), ('oftalmologia', 'Oftalmologia'), ('oncologia', 'Oncologia'), ('ortopedia', 'Ortopedia'), ('pediatria', 'Pediatria'), ('pneumologia', 'Pneumologia'), ('psiquiatria', 'Psiquiatria'), ('urologia', 'Urologia'), ('anestesiologia', 'Anestesiologia'), ('radiologia', 'Radiologia'), ('patologia', 'Patologia'), ('medicina_geral', 'Medicina Geral'), ('saude_publica', 'Saúde Pública'), ('enfermagem', 'Enfermagem'), ('fisioterapia', 'Fisioterapia'), ('farmacia', 'Farmácia'), ('nutricao', 'Nutrição'), ('odontologia', 'Odontologia'), ('medicina_veterinaria', 'Medicina Veterinária'), ('tecnologia_saude', 'Tecnologia em Saúde'), ('outros', 'Outros')], max_length=50),
        ),
    ]
