# Generated by Django 5.2 on 2025-10-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0022_alter_article_research_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='qualis_capes',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('C', 'C')], default='C', max_length=2, verbose_name='Qualis Capes'),
        ),
    ]
