# Generated by Django 5.2 on 2025-10-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_article_qualis_capes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.AlterField(
            model_name='article',
            name='qualis_capes',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('C', 'C')], default='A1', max_length=2, verbose_name='Qualis Capes'),
        ),
    ]
