# Generated by Django 5.2 on 2025-10-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_remove_article_access_type_remove_article_price_and_more'),
    ]

    operations = [
    ]
