# Generated by Django 5.2 on 2025-10-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0026_mediapost_research_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='research_area',
            field=models.CharField(choices=[('anestesiologia', 'Anestesiologia'), ('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('endocrinologia', 'Endocrinologia'), ('enfermagem', 'Enfermagem'), ('farmacia', 'Farmácia'), ('fisioterapia', 'Fisioterapia'), ('gastroenterologia', 'Gastroenterologia'), ('ginecologia', 'Ginecologia e Obstetrícia'), ('medicina_geral', 'Medicina Geral'), ('medicina_veterinaria', 'Medicina Veterinária'), ('neurologia', 'Neurologia'), ('nutricao', 'Nutrição'), ('odontologia', 'Odontologia'), ('oftalmologia', 'Oftalmologia'), ('oncologia', 'Oncologia'), ('ortopedia', 'Ortopedia'), ('patologia', 'Patologia'), ('pediatria', 'Pediatria'), ('pneumologia', 'Pneumologia'), ('psiquiatria', 'Psiquiatria'), ('radiologia', 'Radiologia'), ('saude_coletiva', 'Saúde Coletiva'), ('saude_publica', 'Saúde Pública'), ('tecnologia_saude', 'Tecnologia em Saúde'), ('urologia', 'Urologia'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='research_area',
            field=models.CharField(choices=[('anestesiologia', 'Anestesiologia'), ('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('endocrinologia', 'Endocrinologia'), ('enfermagem', 'Enfermagem'), ('farmacia', 'Farmácia'), ('fisioterapia', 'Fisioterapia'), ('gastroenterologia', 'Gastroenterologia'), ('ginecologia', 'Ginecologia e Obstetrícia'), ('medicina_geral', 'Medicina Geral'), ('medicina_veterinaria', 'Medicina Veterinária'), ('neurologia', 'Neurologia'), ('nutricao', 'Nutrição'), ('odontologia', 'Odontologia'), ('oftalmologia', 'Oftalmologia'), ('oncologia', 'Oncologia'), ('ortopedia', 'Ortopedia'), ('patologia', 'Patologia'), ('pediatria', 'Pediatria'), ('pneumologia', 'Pneumologia'), ('psiquiatria', 'Psiquiatria'), ('radiologia', 'Radiologia'), ('saude_coletiva', 'Saúde Coletiva'), ('saude_publica', 'Saúde Pública'), ('tecnologia_saude', 'Tecnologia em Saúde'), ('urologia', 'Urologia'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Área de Pesquisa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='area_pesquisa',
            field=models.CharField(choices=[('anestesiologia', 'Anestesiologia'), ('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('endocrinologia', 'Endocrinologia'), ('enfermagem', 'Enfermagem'), ('farmacia', 'Farmácia'), ('fisioterapia', 'Fisioterapia'), ('gastroenterologia', 'Gastroenterologia'), ('ginecologia', 'Ginecologia e Obstetrícia'), ('medicina_geral', 'Medicina Geral'), ('medicina_veterinaria', 'Medicina Veterinária'), ('neurologia', 'Neurologia'), ('nutricao', 'Nutrição'), ('odontologia', 'Odontologia'), ('oftalmologia', 'Oftalmologia'), ('oncologia', 'Oncologia'), ('ortopedia', 'Ortopedia'), ('patologia', 'Patologia'), ('pediatria', 'Pediatria'), ('pneumologia', 'Pneumologia'), ('psiquiatria', 'Psiquiatria'), ('radiologia', 'Radiologia'), ('saude_coletiva', 'Saúde Coletiva'), ('saude_publica', 'Saúde Pública'), ('tecnologia_saude', 'Tecnologia em Saúde'), ('urologia', 'Urologia'), ('outros', 'Outros')], max_length=50, verbose_name='Área de Pesquisa'),
        ),
    ]
