# Generated by Django 5.2 on 2025-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0027_alter_article_research_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymessage',
            name='pdf',
            field=models.FileField(blank=True, help_text='Arquivos permitidos: PDF, imagens, documentos Word, arquivos de texto', null=True, upload_to='community_messages/', verbose_name='Arquivo'),
        ),
    ]
