# Generated by Django 5.2 on 2025-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Instituição"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="research_area",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Área de Pesquisa"
            ),
        ),
    ]
