# Generated by Django 4.1 on 2025-08-17 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0002_remove_user_research_areas_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Área de Pesquisa',
                'verbose_name_plural': 'Áreas de Pesquisa',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('In', 'Sou uma pesquisador(a) ou inovador(a)'), ('Re', 'Não sou inovador(a), meu interesse é ler conteúdo')], default='Re', max_length=20),
        ),
        migrations.CreateModel(
            name='InnovatorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('INDIVIDUAL', 'Pessoa Física'), ('COMPANY', 'Empresa/Instituição')], max_length=12)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(upload_to='verification_docs/', validators=[user.models.validate_doc_extension, user.models.validate_doc_size])),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_areas', models.ManyToManyField(to='innovator.researcharea')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='innovator_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
