# Generated by Django 4.1 on 2025-08-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0004_user_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovatorverification',
            name='research_areas',
        ),
    ]
