# Generated by Django 4.1 on 2025-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0005_remove_innovatorverification_research_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovatorverification',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
