# Generated by Django 4.1 on 2025-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0007_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
