# Generated by Django 4.1 on 2025-09-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
