# Generated by Django 4.1 on 2025-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0009_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovatorverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResearchArea',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='InnovatorVerification',
        ),
    ]
