# Generated by Django 5.2 on 2025-09-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("innovator", "0010_remove_innovatorverification_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="title",
        ),
    ]
