# Generated by Django 5.2.4 on 2025-07-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='research_areas',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Re', 'Reader'), ('In', 'Innovator')], default='Re', max_length=20),
        ),
        migrations.DeleteModel(
            name='ResearchArea',
        ),
    ]
